[package]
name = "rufin-test-support"
version = "0.1.5"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
async-trait = "0.1.89"
rufin-core = { path = "../rufin-core" }
rufin-provider = { path = "../rufin-provider" }

[dev-dependencies]
futures-executor = "0.3.32"

[lints]
workspace = true
