#!/bin/sh

for index in 0 1 2 3 4 5 6 7 8 9; do
    if [ ! -S "${XDG_RUNTIME_DIR}/discord-ipc-${index}" ]; then
        ln -sf "app/com.discordapp.Discord/discord-ipc-${index}" "${XDG_RUNTIME_DIR}/discord-ipc-${index}"
    fi
done

export RUFIN_LOCALEDIR="${RUFIN_LOCALEDIR:-/app/share/locale}"

exec /app/bin/rufin.bin "$@"
