[package]
name = "secrets"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true
publish.workspace = true

[dependencies]
base64.workspace = true
domain.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[target.'cfg(unix)'.dependencies]
oo7.workspace = true
tokio = { workspace = true, features = ["rt", "time"] }

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
