[package]
name = "rufin-secrets"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
rufin-core = { path = "../rufin-core" }
thiserror = "2.0.18"

[target.'cfg(unix)'.dependencies]
oo7 = "0.6.0"
tokio = { version = "1.52.3", features = ["rt", "time"] }

[lints]
workspace = true
