experimental-features = nix-command flakes
sandbox = false
build-users-group =
connect-timeout = 10
download-attempts = 5
extra-substituters = https://rufin.cachix.org
extra-trusted-public-keys = rufin.cachix.org-1:7+XHqna/b9jZpCorYvZIoE0UjLju4IKbXlJGt35+SNc=
stalled-download-timeout = 90
