#!/usr/bin/env bash
set -euo pipefail

mode="$1"
shift
if [[ "$mode" == "nix" ]]; then
  nix_target="$1"
  shift
fi

if [[ $# -eq 4 && "$1" == rustup && "$2" == toolchain && "$3" == list && "$4" == --quiet ]]; then
  exit 0
fi

if [[ "$mode" == "nix" ]]; then
  exec nix --accept-flake-config develop "$nix_target" --command "$@"
fi

exec "$@"
