[package]
name = "playback"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true
publish.workspace = true

[dependencies]
gstreamer = { workspace = true, features = ["v1_26"] }
gstreamer-audio = { workspace = true, features = ["v1_26"] }
gstreamer-play = { workspace = true, features = ["v1_26"] }
domain.workspace = true
rustfft.workspace = true
thiserror.workspace = true
tracing.workspace = true

[lints]
workspace = true
